title: Lantern Studios
description: Lantern Studios Docs
theme: just-the-docs

url: https://lanterngamestudios.github.io

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template
